### ISSUE TITLE
アプリケーションのDocker化

### ISSUE THREAD

**Issue by ucchy84** [ucchy84/todo-app#1]
ReactをDockerでコンテナを作成し、アプリケーションを立ち上げることができる．

`node version: 15-alpine3.10`

**Comment by ucchy84** [comment]
まずは、Dockerfileを作成する．今回はnodeのalpine版を利用．

```docker
FROM node:15-alpine3.10
WORKDIR /usr/src/app
```

**Comment by ucchy84** [comment]
`compose.yml`も↓のようにした

```yaml
version: '3'
services: 
  todo-app:
    container_name: todo-app
    build: .
    volumes: 
      - ./:usr/src/app
    command: ash -c "cd workplace && yarn start"
    ports:
      - '3000:3000'
    tty: true
```

**Comment by ucchy84** [comment]
docker-composeでビルド
```bash
docker-compose build
```

Reactとcreate-react-appをインストール＋アプリ作成

```bash
docker-compose run --rm react sh -c "npm install -g create-react-app && create-react-app workplace"
```

**Comment by ucchy84** [comment]
うまく、アプリケーションが作成されそう．

**Comment by ucchy84** [comment]
うーーん、今のままだとdockerfileとかもマウントされているな．これって必要ないかも．`workplace`配下だけで良さそうなので、
`docker-compose.yml`ファイルを以下のように修正

```yaml
version: '3'
services: 
  app:
    container_name: todo-app
    build: .
    volumes: 
     # 修正
      - ./workplace/:usr/src/app
    command: ash -c "cd workplace && yarn start"
    ports:
      - '3000:3000'
    tty: true
```

として、`docker-compose build`でビルドしなおす．
