### ISSUE TITLE
golangでAPI設計

### ISSUE THREAD

**Issue by ucchy84** [ucchy84/todo-app#15]
docker + golangでAPIを実装してみる．
CRUDな感じで行うつもり．

とりあえず、todoアプリを完成させる．

**Comment by ucchy84** [comment]
```dockerfile:Dockerfile
FROM golang:1.16-alpine

WORKDIR /gor/src/app
COPY . .

RUN apk update && \
apk add --no-cache git curl

RUN go get github.com/go-sql-driver/mysql
RUN go get github.com/jinzhu/gorm
RUN go get github.com/gorilla/mux
```

```yml:docker-compose.yml
version: '3'
services:
  go:
    build: .
    volumes:
      - ./:/go/src/app
    command: ash -c "go run main.go"
    tty: true
    ports:
      - 8080:8080
    depends_on:
      - "db"
  db:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_database
      MYSQL_USER: go_test
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db: ~
```
